name: CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy
              uses: cloud run
              with:
                    region: us-southeast2
                    platform: managed
                    memory: 512Mi
                    cpu: 1
                    port: 8000
                    concurrency: 80
                    max-instances: 1
                    min-instances: 1
                    timeout: 300
                    allow-unauthenticated: true